# Nome do arquivo: docker-compose.prod.yml
services:
  db:
    image: postgres:16-alpine
    container_name: cyrius-db
    restart: always
    env_file: .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cyrius-redis
    restart: always

  backend:
    # Baixa a imagem pronta (Sem build local)
    image: cyriusdev25/cyrius-backend:latest
    container_name: cyrius-backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    # Apenas volumes de DADOS, nada de c√≥digo
    volumes:
      - media_volume_prod:/app/media
      - static_volume_prod:/app/static

  nginx:
    # Baixa a imagem pronta do frontend
    image: cyriusdev25/cyrius-frontend:latest
    container_name: cyrius-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volume_prod:/app/media
      - static_volume_prod:/app/static
    depends_on:
      - backend

volumes:
  postgres_data_prod:
  media_volume_prod:
  static_volume_prod: