# Nome do arquivo: docker-compose.dev.yml
services:
  db:
    image: postgres:16-alpine
    container_name: cyrius-db-dev
    env_file: .env
    ports:
      - "5432:5432" # Apenas no DEV
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cyrius-redis-dev
    ports:
      - "6379:6379" # Apenas no DEV

  backend:
    build:
      context: ./backend
    container_name: cyrius-backend-dev
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" # DEV only
    volumes:
      - ./backend:/app            # HOT RELOAD
      - media_volume_dev:/app/media
      - static_volume_dev:/app/static
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./frontend
    container_name: cyrius-gateway-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volume_dev:/app/media
      - static_volume_dev:/app/static
    depends_on:
      - backend

volumes:
  postgres_data_dev:
  media_volume_dev:
  static_volume_dev:
