version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: cyrius-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    image: cyriusdev25/cyrius-backend:latest
    container_name: cyrius-backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volume:/app/media
      - static_django_volume:/app/static
    restart: always

  # Unificamos o Frontend e o Nginx
  # Usamos a imagem do seu frontend como o servidor principal
  nginx:
    image: cyriusdev25/cyrius-frontend:latest
    container_name: cyrius-gateway
    ports:
      - "80:80"
    volumes:
      # Montamos apenas a configuração e os arquivos de mídia/estáticos do Django
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - static_django_volume:/app/static
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  media_volume:
  static_django_volume: