version: '3.8'

services:
  # --- BANCO DE DADOS ---
  db:
    image: postgres:16-alpine
    container_name: cyrius_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
    restart: always

  # --- CACHE ---
  redis:
    image: redis:7-alpine
    container_name: cyrius_redis
    restart: always

  # --- DJANGO BACKEND ---
  backend:
    # Agora puxamos a imagem pronta do seu Docker Hub
    image: cyriusdev25/cyrius-backend:latest
    container_name: cyrius_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    # Volumes persistentes (Nomeados) para não perder arquivos ao atualizar a imagem
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - fotos_equipe_volume:/app/fotos_equipe
      - docs_estoque_volume:/app/docs_estoque
      - financeiro_volume:/app/financeiro
      - contratos_volume:/app/contratos
      - servicos_docs_volume:/app/servicos_docs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  # --- FRONTEND + NGINX (Unificados) ---
  frontend:
    # Esta imagem conterá o React Buildado E o Nginx configurado
    image: cyriusdev25/cyrius-frontend:latest
    container_name: cyrius_frontend
    ports:
      - "80:80"
    # Montamos os volumes do backend aqui apenas para o Nginx servir os arquivos (Read Only)
    volumes:
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
      - fotos_equipe_volume:/app/fotos_equipe:ro
      - docs_estoque_volume:/app/docs_estoque:ro
    depends_on:
      - backend
    restart: always

# Definição dos volumes persistentes (Gerenciados pelo Docker)
volumes:
  postgres_data:
  static_volume:
  media_volume:
  fotos_equipe_volume:
  docs_estoque_volume:
  financeiro_volume:
  contratos_volume:
  servicos_docs_volume: